### ISSUE TITLE
add pkg orthoDr

### ISSUE THREAD

**Issue by FlorianSchwendinger** [cran-task-views/Optimization#18]
Add package **orthoDr** for more information see [RJ-2019-006](https://journal.r-project.org/archive/2019/RJ-2019-006/index.html).

**Comment by hwborchers** [comment]
I am a bit against this package on the Task View, as it solves an application problem, not an optimization problem per se. There are many more packages on CRAN of this kind, that we have not listed, and the Task View is too voluminous.
