### ISSUE TITLE
add highs package

### ISSUE THREAD

**Issue by FlorianSchwendinger** [cran-task-views/Optimization#23]

**Comment by hwborchers** [comment]
I tried to install the 'highs' ROI plugin and was unsuccessful. The "Download" button on the HiGHS development page returns an "Error 404". And on the Installation page, it points to

    https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl/releases

where it is unclear (to me, at least), which of the Linux downloads is right for my Debian 11 Linux system.

In Julia, when I download the Highs.jl package the HiGHS binary is also installed on my system -- but unfortunately not usuable for the Roi plugin. Would it be possible to install HiGHS together with the plugin?

**Comment by FlorianSchwendinger** [comment]
You just need to type
```r
install.packages("ROI.plugin.highs")
```
The HiGHS library is delivered with the **highs** package. On unix the installation takes 2 minutes.

Since the source of the HiGHS library is included in the inst folder of package **HiGHS** if you get 404 this would mean that CRAN is not reachable from your PC. Since the installation of the package source does not require an internet connection.

**Comment by FlorianSchwendinger** [comment]
resolved with merger #27

**Comment by hwborchers** [comment]
install.packages("ROI.plugin.highs")
Installing package into ‘/home/hwb/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
also installing the dependency ‘highs’

trying URL 'https://cloud.r-project.org/src/contrib/highs_0.1-6.tar.gz'
Content type 'application/x-gzip' length 1155146 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

trying URL 'https://cloud.r-project.org/src/contrib/ROI.plugin.highs_1.0-2.tar.gz'
Content type 'application/x-gzip' length 5905 bytes
==================================================
downloaded 5905 bytes

* installing *source* package ‘highs’ ...
** package ‘highs’ successfully unpacked and MD5 sums checked
** using staged installation
Use 'configure'
Could not find 'cmake'!
ls: cannot access '/tmp/Rtmpuza81X/R.INSTALL890a38c6bb10/highs/src/highslib': No such file or directory
'HiGHS' libraries could not be found!
ERROR: configuration failed for package ‘highs’
* removing ‘/home/hwb/R/x86_64-pc-linux-gnu-library/4.2/highs’
Warning in install.packages :
  installation of package ‘highs’ had non-zero exit status
ERROR: dependency ‘highs’ is not available for package ‘ROI.plugin.highs’
* removing ‘/home/hwb/R/x86_64-pc-linux-gnu-library/4.2/ROI.plugin.highs’
Warning in install.packages :
  installation of package ‘ROI.plugin.highs’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpOC9gcS/downloaded_packages’

**Comment by hwborchers** [comment]
After having installed 'cmake' on my Linux system, the installation of 'ROI.plugin.highs' went through.
The question really is: After having installed hundreds of R packages with binary components, why is this the first time I have to use 'cmake'?

**Comment by FlorianSchwendinger** [comment]
Sorry for the late reply. I did not see the question.

> After having installed 'cmake' on my Linux system, the installation of 'ROI.plugin.highs' went through. The question really is: After having installed hundreds of R packages with binary components, why is this the first time I have to use 'cmake'?

In short many optimization packages use cmake to build the C++ library, e.g., **nloptr**, **scs**, **highs**, ...
If you never hat to install it, it either was installed or you used a pre-compiled version, I don't know. But you need it for many **R** packages.
I my self would always avoid cmake in an **R** package if possible, but if a C/C++ library I link to uses cmake to build the library it is typically much work to get rid of the cmake.
