### ISSUE TITLE
add calibrar package

### ISSUE THREAD

**Issue by Beliavsky** [cran-task-views/Optimization#38]
I suggest adding the calibrar package https://cran.r-project.org/web/packages/calibrar/index.html to the Optimization task view, perhaps in the [Global and Stochastic Optimization](https://cran.r-project.org/web/views/Optimization.html#global-and-stochastic-optimization) section.

**Comment by hwborchers** [comment]
Thanks for pointing out the 'calibrar' package;
it will be added to the next version of the Task View.
