### ISSUE TITLE
add package genetic.algo.optimizeR

### ISSUE THREAD

**Issue by Beliavsky** [cran-task-views/Optimization#39]
I suggest adding the package genetic.algo.optimizeR https://cran.r-project.org/web/packages/genetic.algo.optimizeR/index.html to the Global and Stochastic Optimization section of the Optimization task view.

**Comment by hwborchers** [comment]
Thanks for pointing out this package;
adding it to the Task View will be postponed
because of questions concerning its quality and usefulness.
