### ISSUE TITLE
Add package mixopt: Mixed Variable Optimization

### ISSUE THREAD

**Issue by Beliavsky** [cran-task-views/Optimization#43]
https://cran.r-project.org/web/packages/mixopt/index.html

Mixopt could be listed among the MIP (Mixed integer programming) packages.

**Comment by hwborchers** [comment]
I can't see whether this is a useful package for optimization or not. 
The documentation is 'lousy'.
If you want it to be added, submit an issue or pull request in the GitHub repository.
This is what the README suggests.
