### ISSUE TITLE
Archived Packages 2022

### ISSUE THREAD

**Issue by hwborchers** [cran-task-views/Optimization#7]
Package 'CLSOCP' got archived on CRAN and has thus been removed from the Task View. 
The first/last version is now 10 years old, we can assume it will not return to CRAN.

    Package: CLSOCP
    Type: Package
    Title: A smoothing Newton method SOCP solver
    Version: 1.0
    Date: 2010-11-05
    Author: Jason Rudy
    Maintainer: Jason Rudy <jcrudy@gmail.com>
    Description: This package provides and implementation of a one step
        smoothing newton method for the solution of second order cone
        programming problems, originally described by Xiaoni Chi and
        Sanyang Liu.

**Comment by hwborchers** [comment]
Package 'optmatch' has been archived and removed from the Task View on Feb. 20.  It returned to CRAN on March 15. We will reintroduce it with the former description.

    Package: optmatch
    Version: 0.10.0
    Title: Functions for Optimal Matching
    Description: Distance based bipartite matching using minimum cost flow, oriented
      to matching of treatment and control groups in observational studies (Hansen
      and Klopfer 2006 <doi:10.1198/106186006X137047>). Routines are provided to
      generate distances from generalised linear models (propensity score
      matching), formulas giving variables on which to limit matched distances,
      stratified or exact matching directives, or calipers, alone or in combination.

**Comment by FlorianSchwendinger** [comment]
**CLSOCP** was archived with commit `2c1409256e4a9da7542e9a57033417695ebbdaf6`.
**optmatch** is back on CRAN.
